apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq.conf: |
    default_user = guest
    default_pass = guest
    default_vhost = /
    log.file.level = info
    queue.initial.queue1 = task
    queue.initial.queue2 = result
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: rabbitmq 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12
        ports:
        - containerPort: 5672
         volumeMounts:
        - name: rabbitmq-config
          mountPath: /etc/rabbitmq
      volumes:
      - name: rabbitmq-config
        configMap:
          name: rabbitmq-config
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rce
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
