apiVersion: apps/v1
kind: Deployment
metadata:
  name: leetcode-server-deployment
  labels:
    app: leetcode-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leetcode-server
  template:
    metadata:
      labels:
        app: leetcode-server
    spec:
      containers:
      - name: leetcode-server
        image: akhilbisht798/leetcode_server:1.0
        ports:
        - containerPort: 3000
        env:
        - name: QUEUE_URL
          valueFrom:
            configMapKeyRef:
              name: leetcode-config
              key: queue_url
---
apiVersion: v1
kind: Service
metadata:
  name: leetcode-service
spec:
  type: NodePort
  selector:
    app: leetcode-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100
