# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  my-server
  namespace: default
  labels:
    app:  my-server
spec:
  selector:
    matchLabels:
      app: my-server
  replicas: 1
  template:
    metadata:
      labels:
        app:  my-server
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  my-server
        image:  myjob:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort:  8080
        envFrom:
          - configMapRef:
            name: server-configmap 
---

